def print_resume():
    print("R E S U M E")
    print("Name: Rafael Louie V. Miguel")
    print("Address: Pasig City")
    print("Shool: Polytechnic University of the Philippines")
    print("Course: Bachelor of Science in Information Technology")
    print("Birthday: July 20, 2003")
    print("Nationality: Filipino")
    print("Religion: Christian")
    print("Phone Number: 09213398014")
    print("Email: miguel.rafaellouie2003@gmail.com")
    print("GitHub Link: https://github.com/egg-lou")
    print("LinkedIn Link: https://www.linkedin.com/in/louiemiguel")
    print("Hobbies: Watching the Primeagen")
    print("Affiliations: AWS Cloud Club Captain")
    print("Projects: Serverless Photobooth Application, Data Scraper for News Website")
    print("Programming Languages: TypeScript, Python, Rust")
    print("Tech Skills: Cloud Computing, Data Scraping, Web Development")
    print("Soft Skills: Leadership, Project Management")
    print("Volunteer Experience: AWS Community Day Philippines 2023 Event Manager and Web Developer")
    print("Certifications:  Technical Support Fundamentals, JavaScript Algorithms and Data Structures")

if __name__ == "__main__":
    print_resume()
